import { ImageSourcePropType } from "react-native";

export const bugArt = {
  "zilvervisje": require("../../assets/bugdex/zilvervisje.png"),
  "fruitvlieg": require("../../assets/bugdex/fruitvlieg.png"),
  "bladluis": require("../../assets/bugdex/bladluis.png"),
  "mug": require("../../assets/bugdex/mug.png"),
  "mot": require("../../assets/bugdex/mot.png"),
  "motmug": require("../../assets/bugdex/motmug.png"),
  "langpootmug": require("../../assets/bugdex/langpootmug.png"),
  "mier": require("../../assets/bugdex/mier.png"),
  "houtmier": require("../../assets/bugdex/houtmier.png"),
  "faraomier": require("../../assets/bugdex/faraomier.png"),
  "vlo": require("../../assets/bugdex/vlo.png"),
  "teek": require("../../assets/bugdex/teek.png"),
  "fluweelmijt": require("../../assets/bugdex/fluweelmijt.png"),
  "pissebed": require("../../assets/bugdex/pissebed.png"),
  "stinkwants": require("../../assets/bugdex/stinkwants.png"),
  "schildwants": require("../../assets/bugdex/schildwants.png"),
  "snuitkever": require("../../assets/bugdex/snuitkever.png"),
  "lieveheersbeestje": require("../../assets/bugdex/lieveheersbeestje.png"),
  "kakkerlak": require("../../assets/bugdex/kakkerlak.png"),
  "oorworm": require("../../assets/bugdex/oorworm.png"),
  "boktor": require("../../assets/bugdex/boktor.png"),
  "tapijtkever": require("../../assets/bugdex/tapijtkever.png"),
  "roofwants": require("../../assets/bugdex/roofwants.png"),
  "duizendpoot": require("../../assets/bugdex/duizendpoot.png"),
  "sprinkhaan": require("../../assets/bugdex/sprinkhaan.png"),
  "wesp": require("../../assets/bugdex/wesp.png"),
  "hoornaar": require("../../assets/bugdex/hoornaar.png"),
  "sluipwesp": require("../../assets/bugdex/sluipwesp.png"),
  "schorpioen": require("../../assets/bugdex/schorpioen.png"),
  "termiet": require("../../assets/bugdex/termiet.png"),
  "mestkever": require("../../assets/bugdex/mestkever.png"),
  "wandelende-tak": require("../../assets/bugdex/wandelende-tak.png"),
  "wandelend-blad": require("../../assets/bugdex/wandelend-blad.png"),
  "vogelspin": require("../../assets/bugdex/vogelspin.png"),
  "reuzenkakkerlak": require("../../assets/bugdex/reuzenkakkerlak.png"),
  "reuzen-duizendpoot": require("../../assets/bugdex/reuzen-duizendpoot.png"),
  "neushoornkever": require("../../assets/bugdex/neushoornkever.png"),
  "atlaskever": require("../../assets/bugdex/atlaskever.png"),
  "herculeskever": require("../../assets/bugdex/herculeskever.png"),
  "goliathkever": require("../../assets/bugdex/goliathkever.png"),
  "vliegend-hert": require("../../assets/bugdex/vliegend-hert.png"),
  "juweelkever": require("../../assets/bugdex/juweelkever.png"),
  "goudtor": require("../../assets/bugdex/goudtor.png"),
  "tijgerkever": require("../../assets/bugdex/tijgerkever.png"),
  "doodgraver": require("../../assets/bugdex/doodgraver.png"),
  "kniptor": require("../../assets/bugdex/kniptor.png"),
  "loopkever": require("../../assets/bugdex/loopkever.png"),
  "waterkever": require("../../assets/bugdex/waterkever.png"),
  "schrijvertje": require("../../assets/bugdex/schrijvertje.png"),
  "schaatsenrijder": require("../../assets/bugdex/schaatsenrijder.png"),
  "waterschorpioen": require("../../assets/bugdex/waterschorpioen.png"),
  "bidsprinkhaan": require("../../assets/bugdex/bidsprinkhaan.png"),
  "wespspin": require("../../assets/bugdex/wespspin.png"),
  "kruisspin": require("../../assets/bugdex/kruisspin.png"),
  "springspin": require("../../assets/bugdex/springspin.png"),
  "libel": require("../../assets/bugdex/libel.png"),
  "waterjuffer": require("../../assets/bugdex/waterjuffer.png"),
  "gaasvlieg": require("../../assets/bugdex/gaasvlieg.png"),
  "doodshoofdvlinder": require("../../assets/bugdex/doodshoofdvlinder.png"),
  "kolibrievlinder": require("../../assets/bugdex/kolibrievlinder.png"),
  "koninginnenpage": require("../../assets/bugdex/koninginnenpage.png"),
  "atalanta": require("../../assets/bugdex/atalanta.png"),
  "dagpauwoog": require("../../assets/bugdex/dagpauwoog.png"),
  "eikenprocessierups": require("../../assets/bugdex/eikenprocessierups.png"),
  "pijlstaartrups": require("../../assets/bugdex/pijlstaartrups.png"),
  "boekluis": require("../../assets/bugdex/boekluis.png"),
  "stofluis": require("../../assets/bugdex/stofluis.png"),
  "cicade": require("../../assets/bugdex/cicade.png"),
  "schuimcicade": require("../../assets/bugdex/schuimcicade.png"),
  "orchidee-bidsprinkhaan": require("../../assets/bugdex/orchidee-bidsprinkhaan.png"),
  "pauwspin": require("../../assets/bugdex/pauwspin.png"),
  "juweelwesp": require("../../assets/bugdex/juweelwesp.png"),
  "goudschildkever": require("../../assets/bugdex/goudschildkever.png"),
  "harlekijnwants": require("../../assets/bugdex/harlekijnwants.png"),
  "lantaarnvlieg": require("../../assets/bugdex/lantaarnvlieg.png"),
  "vioolspin": require("../../assets/bugdex/vioolspin.png"),
  "gespikkelde-houtvlinder": require("../../assets/bugdex/gespikkelde-houtvlinder.png"),
  "zebra-springspin": require("../../assets/bugdex/zebra-springspin.png"),
  "smaragdlibel": require("../../assets/bugdex/smaragdlibel.png"),
  "glasvleugelvlinder": require("../../assets/bugdex/glasvleugelvlinder.png"),
  "komeetmot": require("../../assets/bugdex/komeetmot.png"),
  "maanmot": require("../../assets/bugdex/maanmot.png"),
  "atlasvlinder": require("../../assets/bugdex/atlasvlinder.png"),
  "rozekever": require("../../assets/bugdex/rozekever.png"),
  "kardinaalkever": require("../../assets/bugdex/kardinaalkever.png"),
  "vuurwants": require("../../assets/bugdex/vuurwants.png"),
  "sabelsprinkhaan": require("../../assets/bugdex/sabelsprinkhaan.png"),
  "mierenleeuw": require("../../assets/bugdex/mierenleeuw.png"),
  "dobsonvlieg": require("../../assets/bugdex/dobsonvlieg.png"),
  "helikopterjuffer": require("../../assets/bugdex/helikopterjuffer.png"),
  "spookinsect": require("../../assets/bugdex/spookinsect.png"),
  "bladpootwants": require("../../assets/bugdex/bladpootwants.png"),
  "assassin-bug": require("../../assets/bugdex/assassin-bug.png"),
  "tijgermug": require("../../assets/bugdex/tijgermug.png"),
  "dolksteekwesp": require("../../assets/bugdex/dolksteekwesp.png"),
  "roofvlieg": require("../../assets/bugdex/roofvlieg.png"),
  "kameelhalsvlieg": require("../../assets/bugdex/kameelhalsvlieg.png"),
  "zweefvlieg": require("../../assets/bugdex/zweefvlieg.png"),
  "goudwesp": require("../../assets/bugdex/goudwesp.png"),
  "fluweelmier": require("../../assets/bugdex/fluweelmier.png"),
  "reuzenwaterwants": require("../../assets/bugdex/reuzenwaterwants.png"),
  "zweepschorpioen": require("../../assets/bugdex/zweepschorpioen.png"),
  "azuren-waterjuffer": require("../../assets/bugdex/azuren-waterjuffer.png"),
  "rouwmantelvlinder": require("../../assets/bugdex/rouwmantelvlinder.png"),
  "keizersmantel": require("../../assets/bugdex/keizersmantel.png"),
  "gouden-tor": require("../../assets/bugdex/gouden-tor.png"),
  "soldaatje": require("../../assets/bugdex/soldaatje.png"),
  "doodgraverkever": require("../../assets/bugdex/doodgraverkever.png"),
  "olifantskever": require("../../assets/bugdex/olifantskever.png"),
  "regenboogmestkever": require("../../assets/bugdex/regenboogmestkever.png"),
  "titanus-kever": require("../../assets/bugdex/titanus-kever.png"),
  "langsprietboktor": require("../../assets/bugdex/langsprietboktor.png"),
  "schildpadkever": require("../../assets/bugdex/schildpadkever.png"),
  "vuurkever": require("../../assets/bugdex/vuurkever.png"),
  "blauwe-ertsbij": require("../../assets/bugdex/blauwe-ertsbij.png"),
  "wespboktor": require("../../assets/bugdex/wespboktor.png"),
  "groene-zandloopkever": require("../../assets/bugdex/groene-zandloopkever.png"),
  "lauwstaartwaterjuffer": require("../../assets/bugdex/lauwstaartwaterjuffer.png"),
  "roodwitte-celspin": require("../../assets/bugdex/roodwitte-celspin.png"),
  "koningin-alexandravlinder": require("../../assets/bugdex/koningin-alexandravlinder.png"),
  "zonsondergangsmot": require("../../assets/bugdex/zonsondergangsmot.png"),
  "picasso-wants": require("../../assets/bugdex/picasso-wants.png"),
  "roze-esdoornmot": require("../../assets/bugdex/roze-esdoornmot.png"),
  "giraffekevertje": require("../../assets/bugdex/giraffekevertje.png"),
  "doornbloembidsprinkhaan": require("../../assets/bugdex/doornbloembidsprinkhaan.png"),
  "lantaarndrager": require("../../assets/bugdex/lantaarndrager.png"),
  "glorieuze-scarabee": require("../../assets/bugdex/glorieuze-scarabee.png"),
  "bromvlieg": require("../../assets/bugdex/Nieuwe map/cropped/bromvlieg.png"),
  "dwergcicade": require("../../assets/bugdex/Nieuwe map/cropped/dwergcicade.png"),
  "groene-junikever": require("../../assets/bugdex/Nieuwe map/cropped/groene-junikever.png"),
  "hommel": require("../../assets/bugdex/Nieuwe map/cropped/hommel.png"),
  "huisvlieg": require("../../assets/bugdex/Nieuwe map/cropped/huisvlieg.png"),
  "kleermot": require("../../assets/bugdex/Nieuwe map/cropped/kleermot.png"),
  "meikever": require("../../assets/bugdex/Nieuwe map/cropped/meikever.png"),
  "schorpioenvlieg": require("../../assets/bugdex/Nieuwe map/cropped/schorpioenvlieg.png"),
  "voorraadmot": require("../../assets/bugdex/Nieuwe map/cropped/voorraadmot.png"),
  "whitefly": require("../../assets/bugdex/Nieuwe map/cropped/whitefly.png"),
  "witte-tijger": require("../../assets/bugdex/Nieuwe map/cropped/witte-tijger.png"),
  "zadelrups": require("../../assets/bugdex/zadelrups.png"),
  "reuzenpantervlinder": require("../../assets/bugdex/reuzenpantervlinder.png"),
  "monarchvlinder": require("../../assets/bugdex/monarchvlinder.png"),
  "zakdrager": require("../../assets/bugdex/zakdrager.png"),
  "gehakkelde-aurelia": require("../../assets/bugdex/gehakkelde-aurelia.png"),
  "blauwe-morpho": require("../../assets/bugdex/blauwe-morpho.png"),
  "spinnendoder": require("../../assets/bugdex/spinnendoder.png"),
  "kameelspin": require("../../assets/bugdex/kameelspin.png"),
  "hooiwagen": require("../../assets/bugdex/hooiwagen.png"),
  "zweepspin": require("../../assets/bugdex/zweepspin.png"),
  "doorncicade": require("../../assets/bugdex/doorncicade.png"),
  "kortschildkever": require("../../assets/bugdex/kortschildkever.png"),
  "uilvlinder": require("../../assets/bugdex/uilvlinder.png"),
  "groot-avondrood": require("../../assets/bugdex/groot-avondrood.png"),
  "alpenboktor": require("../../assets/bugdex/alpenboktor.png"),
  "veenmol": require("../../assets/bugdex/veenmol.png"),
  "schietmot": require("../../assets/bugdex/schietmot.png"),
  "eendagsvlieg": require("../../assets/bugdex/eendagsvlieg.png"),
  "oranjetipje": require("../../assets/bugdex/oranjetipje.png"),
  "kleine-vuurvlinder": require("../../assets/bugdex/kleine-vuurvlinder.png"),
  "dikkopje": require("../../assets/bugdex/dikkopje.png"),
  "veldkrekel": require("../../assets/bugdex/veldkrekel.png"),
  "coloradokever": require("../../assets/bugdex/coloradokever.png"),
  "meeltor": require("../../assets/bugdex/meeltor.png"),
  "roodbruine-rijstmeelkever": require("../../assets/bugdex/roodbruine-rijstmeelkever.png"),
  "schorskever": require("../../assets/bugdex/schorskever.png"),
  "glimworm": require("../../assets/bugdex/glimworm.png"),
  "zijdevlinder": require("../../assets/bugdex/zijdevlinder.png"),
  "gevlekte-komkommerkever": require("../../assets/bugdex/gevlekte-komkommerkever.png"),
  "gestreepte-komkommerkever": require("../../assets/bugdex/gestreepte-komkommerkever.png"),
  "oliekever": require("../../assets/bugdex/oliekever.png"),
  "groentje": require("../../assets/bugdex/groentje.png"),
  "heideblauwtje": require("../../assets/bugdex/heideblauwtje.png"),
  "grote-weerschijnvlinder": require("../../assets/bugdex/grote-weerschijnvlinder.png"),
  "bruin-zandoogje": require("../../assets/bugdex/bruin-zandoogje.png"),
  "kraamwebspin": require("../../assets/bugdex/kraamwebspin.png"),
  "groene-krabspin": require("../../assets/bugdex/groene-krabspin.png"),
  "honingbij": require("../../assets/bugdex/honingbij.png"),
  "dambordvlieg": require("../../assets/bugdex/dambordvlieg.png"),
  "ligusterpijlstaart": require("../../assets/bugdex/ligusterpijlstaart.png"),
  "dorbladbidsprinkhaan": require("../../assets/bugdex/dorbladbidsprinkhaan.png"),
  "roze-sprinkhaan": require("../../assets/bugdex/roze-sprinkhaan.png"),
  "gouden-vogelvlinder": require("../../assets/bugdex/gouden-vogelvlinder.png"),
  "pauwoogpijlstaart": require("../../assets/bugdex/pauwoogpijlstaart.png"),
  "smaragd-springspin": require("../../assets/bugdex/smaragd-springspin.png")
} as const satisfies Record<string, ImageSourcePropType>;

export type BugArtId = keyof typeof bugArt;

export const allBugArtIds = Object.keys(bugArt) as BugArtId[];

export const tierBugArtIds: BugArtId[] = [
  "zilvervisje",
  "houtmier",
  "bidsprinkhaan",
  "orchidee-bidsprinkhaan",
  "smaragdlibel",
  "schorpioen",
  "olifantskever",
  "titanus-kever",
  "herculeskever",
  "juweelkever",
  "reuzenpantervlinder",
  "gouden-vogelvlinder"
];

export function getBugArtSource(id: string | undefined): ImageSourcePropType | null {
  if (!id) return null;
  return (bugArt as Record<string, ImageSourcePropType>)[id] ?? null;
}
