import { ArenaBug, ArenaSpecies, ArenaStats, ArenaType, SquadSnapshot } from "./bugSquadArenaTypes";

export const levelThresholds = [0, 0, 100, 240, 430, 680, 1000, 1400, 1900, 2500, 3300];
export const typeColors: Record<ArenaType, string> = { Crash: "#ff6b3d", Leak: "#63f6a1", Glitch: "#b58cff", Security: "#ffd166", Patch: "#48dcff" };

const m = (id: string, name: string, kind: "basic" | "skill" | "ultimate", type: ArenaType, power: number, cost: number, unlockLevel: number, effect = {}) => ({ id, name, description: name, kind, type, power, accuracy: kind === "ultimate" ? 86 : 94, cost, unlockLevel, target: power > 0 ? "enemy" as const : "self" as const, effect });
const s = (speciesId: string, displayName: string, sourceBugArtId: ArenaSpecies["sourceBugArtId"], type: ArenaType, role: ArenaSpecies["role"], rarity: ArenaSpecies["rarity"], baseStats: ArenaStats, moves: ArenaSpecies["moves"], passive: string): ArenaSpecies => ({ speciesId, displayName, sourceBugArtId, type, role, rarity, baseStats, moves, passive });

export const species: ArenaSpecies[] = [
  s("zilvervisje-byte", "Zilvervisje Byte", "zilvervisje", "Glitch", "Speed", "Gewoon", { maxHp: 72, attack: 18, defense: 8, speed: 32, accuracy: 94, critRate: 12 }, [m("byte", "Byte Nip", "basic", "Glitch", 30, 0, 1), m("phase", "Phase Skitter", "skill", "Glitch", 0, 2, 2, { dodge: 1, shield: 12 }), m("null", "Null Burst", "ultimate", "Glitch", 85, 4, 4, { stun: 25 })], "First hit crit boost."),
  s("atlas-crashodon", "Atlas Crashodon", "atlaskever", "Crash", "Tank", "Legendarisch", { maxHp: 145, attack: 25, defense: 24, speed: 8, accuracy: 90, critRate: 6 }, [m("slam", "System Slam", "basic", "Crash", 34, 0, 1), m("roar", "Crash Roar", "skill", "Crash", 25, 2, 2, { attackDown: 20 }), m("core", "Core Break", "ultimate", "Crash", 110, 4, 4, { recoil: 8 })], "Tough under low HP."),
  s("bladluis-leakling", "Bladluis Leakling", "bladluis", "Leak", "Striker", "Gewoon", { maxHp: 86, attack: 21, defense: 12, speed: 18, accuracy: 92, critRate: 8 }, [m("drip", "Drip Bite", "basic", "Leak", 28, 0, 1), m("leak", "Memory Leak", "skill", "Leak", 18, 2, 2, { poison: 3 }), m("overflow", "Overflow", "ultimate", "Leak", 72, 4, 4, { poison: 3, slow: 3 })], "Poison specialist."),
  s("lieveheers-patchling", "Lieveheers Patchling", "lieveheersbeestje", "Patch", "Support", "Gewoon", { maxHp: 94, attack: 14, defense: 15, speed: 16, accuracy: 96, critRate: 5 }, [m("fix", "Quick Fix", "basic", "Patch", 20, 0, 1, { heal: 6 }), m("shield", "Shield Patch", "skill", "Patch", 0, 2, 2, { shield: 36 }), m("hotfix", "Full Hotfix", "ultimate", "Patch", 0, 4, 4, { heal: 48 })], "Healing boost."),
  s("schorpioen-trojanox", "Schorpioen Trojanox", "schorpioen", "Security", "Striker", "Episch", { maxHp: 116, attack: 30, defense: 18, speed: 12, accuracy: 86, critRate: 10 }, [m("spear", "Spear Packet", "basic", "Security", 36, 0, 1), m("backdoor", "Backdoor Strike", "skill", "Security", 58, 2, 2), m("root", "Root Access", "ultimate", "Security", 118, 4, 4)], "Crit pierces defense."),
  s("waterkever-cachecrab", "Waterkever Cachecrab", "waterkever", "Patch", "Tank", "Zeldzaam", { maxHp: 124, attack: 16, defense: 25, speed: 7, accuracy: 93, critRate: 3 }, [m("claw", "Claw Sync", "basic", "Patch", 26, 0, 1), m("cache", "Cache Shield", "skill", "Patch", 0, 2, 2, { shield: 48 }), m("restore", "Restore Point", "ultimate", "Patch", 0, 4, 4, { heal: 30, shield: 40 })], "Starts shielded.")
];

export const starterSpeciesIds = ["zilvervisje-byte", "bladluis-leakling", "lieveheers-patchling", "waterkever-cachecrab"];
export const defaultActiveSquadSpeciesIds = ["zilvervisje-byte", "bladluis-leakling", "lieveheers-patchling"];
export function getSpecies(id: string) { return species.find((item) => item.speciesId === id) ?? species[0]; }
export function statsAtLevel(base: ArenaStats, level: number): ArenaStats { const l = Math.max(1, level) - 1; return { ...base, maxHp: base.maxHp + l * 11, attack: base.attack + l * 3, defense: base.defense + l * 2, speed: base.speed + Math.floor(l * 1.5) }; }
export function createArenaBug(speciesId: string, level = 1, unlocked = true): ArenaBug { const item = getSpecies(speciesId); return { ...item, instanceId: `${speciesId}-${level}-${Math.random().toString(36).slice(2, 8)}`, level, xp: levelThresholds[level] ?? 0, unlocked, stats: statsAtLevel(item.baseStats, level) }; }
export function getTeamPower(bugs: ArenaBug[]) { return bugs.reduce((sum, bug) => sum + bug.stats.maxHp + bug.stats.attack * 8 + bug.stats.defense * 7 + bug.stats.speed * 5 + bug.level * 60, 0); }
export function getTypeMultiplier(a: ArenaType, d: ArenaType) { if ((a === "Crash" && d === "Glitch") || (a === "Leak" && d === "Crash") || (a === "Glitch" && d === "Security") || (a === "Security" && d === "Leak") || (a === "Patch" && (d === "Crash" || d === "Leak"))) return 1.35; if ((a === "Crash" && (d === "Leak" || d === "Patch")) || (a === "Leak" && (d === "Security" || d === "Patch")) || (a === "Glitch" && d === "Crash") || (a === "Security" && d === "Glitch") || (a === "Patch" && d === "Security")) return 0.75; return 1; }
export function mockEnemySnapshots(): SquadSnapshot[] { const now = new Date().toISOString(); const mk = (name: string, ids: string[], level: number) => { const bugs = ids.map((id) => createArenaBug(id, level, true)); return { snapshotId: `mock-${name}`, ownerPlayerId: `mock-${name}`, ownerDisplayName: name, createdAt: now, teamPower: getTeamPower(bugs), bugs, source: "mock" as const }; }; return [mk("Rookie Remco", ["zilvervisje-byte", "bladluis-leakling", "lieveheers-patchling"], 1), mk("Patch Pro", ["lieveheers-patchling", "waterkever-cachecrab", "zilvervisje-byte"], 3), mk("Crash King", ["atlas-crashodon", "schorpioen-trojanox", "bladluis-leakling"], 4)]; }
